;; ~/.dots/dotfiles/packages.scm
(define-module (dotfiles packages)
  #:use-module (gnu packages)
  #:export (%home-packages))

(define %home-packages
  (specifications->packages
    (list
      "brave-origin-bin"
      "fresh-editor"
      "glow"
      "claude-code"
      "ghostty"
      "icecat"
      "git"
      "micro"
      "make"
      "curl"
      "bat"
      "socat"
      "pandoc"
      "ripgrep"
      "tig"
      "w3m"
      "nb"
      "guile-lsp-server"
      "pinentry-qt"
      "keychain"
      "jq"
      "swaylock-effects"
      "foot"
      "wmenu"
      "gnupg"
      "password-store"
      "playerctl"
      "wireplumber"
      "dbus"
      "node"
      "glibc"
      "lxqt-policykit"
      "swaynotificationcenter"
      "xdg-desktop-portal"
      "xdg-desktop-portal-wlr"
      "xdg-desktop-portal-gtk"
      "kanshi"
      "grim"
      "slurp"
      "wl-clipboard"
      "clipman"
      "hicolor-icon-theme"
      "adwaita-icon-theme"
      "breeze-icons"
      "font-dejavu"
      "font-google-noto"
      "font-google-noto-emoji"
      "font-google-noto-sans-cjk"
      "font-liberation"
      "font-fira-code")))
